// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fastCDF_wrapper
NumericVector fastCDF_wrapper(NumericMatrix p_x_r, Rcpp::List p_z_r, NumericVector p_y_r);
RcppExport SEXP _Hausdorff_fastCDF_wrapper(SEXP p_x_rSEXP, SEXP p_z_rSEXP, SEXP p_y_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type p_x_r(p_x_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type p_z_r(p_z_rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p_y_r(p_y_rSEXP);
    rcpp_result_gen = Rcpp::wrap(fastCDF_wrapper(p_x_r, p_z_r, p_y_r));
    return rcpp_result_gen;
END_RCPP
}
// fastCDFOnSample_wrapper
NumericVector fastCDFOnSample_wrapper(NumericMatrix p_x_r, NumericVector p_y_r);
RcppExport SEXP _Hausdorff_fastCDFOnSample_wrapper(SEXP p_x_rSEXP, SEXP p_y_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type p_x_r(p_x_rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p_y_r(p_y_rSEXP);
    rcpp_result_gen = Rcpp::wrap(fastCDFOnSample_wrapper(p_x_r, p_y_r));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Hausdorff_fastCDF_wrapper", (DL_FUNC) &_Hausdorff_fastCDF_wrapper, 3},
    {"_Hausdorff_fastCDFOnSample_wrapper", (DL_FUNC) &_Hausdorff_fastCDFOnSample_wrapper, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_Hausdorff(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
