// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fastCDF
ArrayXd fastCDF(const ArrayXXd& p_x, const vector< shared_ptr<ArrayXd> >& p_z, const ArrayXd& p_y);
RcppExport SEXP _Hausdorff_fastCDF(SEXP p_xSEXP, SEXP p_zSEXP, SEXP p_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const ArrayXXd& >::type p_x(p_xSEXP);
    Rcpp::traits::input_parameter< const vector< shared_ptr<ArrayXd> >& >::type p_z(p_zSEXP);
    Rcpp::traits::input_parameter< const ArrayXd& >::type p_y(p_ySEXP);
    rcpp_result_gen = Rcpp::wrap(fastCDF(p_x, p_z, p_y));
    return rcpp_result_gen;
END_RCPP
}
// fastCDFOnSample
ArrayXd fastCDFOnSample(const Eigen::ArrayXXd& p_x, const Eigen::ArrayXd& p_y);
RcppExport SEXP _Hausdorff_fastCDFOnSample(SEXP p_xSEXP, SEXP p_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type p_x(p_xSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type p_y(p_ySEXP);
    rcpp_result_gen = Rcpp::wrap(fastCDFOnSample(p_x, p_y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Hausdorff_fastCDF", (DL_FUNC) &_Hausdorff_fastCDF, 3},
    {"_Hausdorff_fastCDFOnSample", (DL_FUNC) &_Hausdorff_fastCDFOnSample, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_Hausdorff(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
