# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

H_stat_2s_1d_tr <- function(a, b) {
    .Call(`_HausdorffGoF_H_stat_2s_1d_tr`, a, b)
}

H_stat_2s_1d_p <- function(a, b) {
    .Call(`_HausdorffGoF_H_stat_2s_1d_p`, a, b)
}

hsearch_Rcpp <- function(x_proj, y_proj) {
    .Call(`_HausdorffGoF_hsearch_Rcpp`, x_proj, y_proj)
}

fastCDF_Rcpp <- function(p_x_r, p_z_r) {
    .Call(`_HausdorffGoF_fastCDF_Rcpp`, p_x_r, p_z_r)
}

fastCDFOnSample_Rcpp <- function(p_x_r) {
    .Call(`_HausdorffGoF_fastCDFOnSample_Rcpp`, p_x_r)
}

