# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

H_stat_2s_1d_tr <- function(a, b) {
    .Call(`_HausdorffGoF_H_stat_2s_1d_tr`, a, b)
}

H_stat_2s_1d_p <- function(a, b) {
    .Call(`_HausdorffGoF_H_stat_2s_1d_p`, a, b)
}

H_stat_2s_2d <- function(x_r, y_r, tol = 1e-6) {
    .Call(`_HausdorffGoF_H_stat_2s_2d`, x_r, y_r, tol)
}

fastCDFOnSample_Rcpp <- function(p_x_r) {
    .Call(`_HausdorffGoF_fastCDFOnSample_Rcpp`, p_x_r)
}

