# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Hausdorff45_Rcpp <- function(a, b) {
    .Call(`_Hausdorff_Hausdorff45_Rcpp`, a, b)
}

Hausdorff_Cpp <- function(a, b) {
    .Call(`_Hausdorff_Hausdorff_Cpp`, a, b)
}

hsearch_Rcpp <- function(x_proj, y_proj, boundary) {
    .Call(`_Hausdorff_hsearch_Rcpp`, x_proj, y_proj, boundary)
}

fastCDF_Rcpp <- function(p_x_r, p_z_r) {
    .Call(`_Hausdorff_fastCDF_Rcpp`, p_x_r, p_z_r)
}

fastCDFOnSample_Rcpp <- function(p_x_r) {
    .Call(`_Hausdorff_fastCDFOnSample_Rcpp`, p_x_r)
}

